2025-04-19 20:45:18,628 - src.utils.data_collection - INFO - 获取CN 2023年的假期数据...
2025-04-19 20:45:18,633 - src.utils.data_collection - INFO - 假期数据已保存到: data/raw/holiday_data.csv
2025-04-19 20:45:56,538 - src.utils.data_collection - INFO - 开始下载酒店预订数据集...
2025-04-19 20:45:56,539 - src.utils.data_collection - ERROR - 下载酒店预订数据集时出错: dataset_download() got an unexpected keyword argument 'dest_path'
2025-04-19 20:46:29,750 - src.utils.data_collection - INFO - 开始下载酒店预订数据集...
2025-04-19 20:46:29,750 - src.utils.data_collection - ERROR - 下载酒店预订数据集时出错: dataset_download() got an unexpected keyword argument 'dest_path'
2025-04-19 20:46:54,309 - src.utils.data_collection - INFO - 开始下载酒店预订数据集...
2025-04-19 20:46:56,153 - src.utils.data_collection - ERROR - 下载酒店预订数据集时出错: 404 Client Error.

Resource not found at URL: https://www.kaggle.com/datasets/jessemostipak/hotel-booking-demand/versions/1
The server reported the following issues: Dataset not found
Please make sure you specified the correct resource identifiers.
2025-04-19 20:56:08,882 - src.utils.data_collection - INFO - 开始下载酒店预订数据集...
2025-04-19 20:56:10,934 - src.utils.data_collection - INFO - 酒店预订数据集已下载到: C:\Users\cheny\.cache\kagglehub\datasets\jessemostipak\hotel-booking-demand\versions\1
2025-04-19 20:56:10,934 - src.utils.data_collection - INFO - 获取区域 (31.24, 31.18, 121.54, 121.46) 的POI数据...
2025-04-19 20:56:10,934 - src.utils.data_collection - ERROR - 获取POI数据时出错: module 'osmnx' has no attribute 'geometries_from_bbox'
2025-04-19 20:56:33,762 - src.utils.data_collection - INFO - 开始下载酒店预订数据集...
2025-04-19 20:56:34,895 - src.utils.data_collection - INFO - 酒店预订数据集已下载到: C:\Users\cheny\.cache\kagglehub\datasets\jessemostipak\hotel-booking-demand\versions\1
2025-04-19 20:56:34,896 - src.utils.data_collection - INFO - 获取区域 (31.24, 31.18, 121.54, 121.46) 的POI数据...
2025-04-19 20:56:34,896 - src.utils.data_collection - ERROR - 获取POI数据时出错: module 'osmnx' has no attribute 'geometries_from_bbox'
2025-04-19 21:03:06,108 - src.utils.data_collection - INFO - 获取区域 (31.24, 31.18, 121.54, 121.46) 的POI数据...
2025-04-19 21:03:06,108 - src.utils.data_collection - ERROR - 获取POI数据时出错: features_from_bbox() takes 2 positional arguments but 5 were given
2025-04-19 21:03:06,206 - pyogrio._io - INFO - Created 200 records
